# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinResult',
            fields=[
                ('coin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coin_name', models.CharField(max_length=50)),
                ('forked', models.BooleanField(default=False)),
                ('rank', models.IntegerField(db_index=True)),
                ('github_id', models.CharField(blank=True, max_length=100)),
                ('github_link', models.CharField(blank=True, max_length=1000)),
                ('total_contributors', models.IntegerField(default=0)),
                ('readme_exists', models.BooleanField(default=False)),
                ('readme_num_lines', models.IntegerField(default=0)),
                ('num_contributors', models.IntegerField(default=0)),
                ('latest_commits', models.DateField(blank=True)),
                ('latest_pr', models.DateField(blank=True)),
                ('num_open_issues', models.IntegerField(default=0)),
                ('num_stars', models.IntegerField(default=0)),
                ('num_watchers', models.IntegerField(default=0)),
                ('num_forks', models.IntegerField(default=0)),
            ],
        ),
    ]
