# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinresult',
            name='is_open_sourced',
            field=models.BooleanField(default=False),
        ),
    ]
