# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_auto_20180303_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinresult',
            name='latest_commits',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coinresult',
            name='latest_pr',
            field=models.DateField(blank=True, null=True),
        ),
    ]
